### ISSUE TITLE
Variable "{{media url="..."}} not working in FAQ

### ISSUE THREAD

**Issue by Tjitse-E** [php-cuong/magento2-faqs-extensions#13]
It seems that the images inserted with the WYSIWYG editor aren't working correctly.

Input:
![edit__lorum_ipsum__1____faqs_manager___magento_admin](https://user-images.githubusercontent.com/14849044/29821880-c5a86272-8cc9-11e7-9f29-3a253e392235.png)

Result:

![developer_tools_-_http___huissteden_dev_faq_test-test-test_html](https://user-images.githubusercontent.com/14849044/29821858-aa8e6c52-8cc9-11e7-80b7-406d6de88fb4.png)

**Comment by php-cuong** [comment]
@Tjitse-E This has been fixed in the version 2.1.3
