### ISSUE TITLE
Module not compatible with M2.2

### ISSUE THREAD

**Issue by Tjitse-E** [php-cuong/magento2-faqs-extensions#15]
Did anyone test if the module works on M2.2?

Trying to run an Magento 2.2  update:
 ```   
- php-cuong/magento2-faqs-extensions 2.1.0 requires magento/module-backend 100.0.*|100.1.*
 -> satisfiable by magento/module-backend[100.1.4, 100.0.4, 100.1.1, 100.0.6, 100.0.11, 100.0.10, 100.1.2, 100.0.2, 100.0.8, 100.1.3, 100.1.0-rc3, 100.0.5, 100.1.0, 100.1.0-rc1, 100.0.7, 100.0.3, 100.0.9, 100.1.0-rc2].
```

**Comment by gewaechshaus** [comment]
@Tjitse-E  - Same result here...

**Comment by woutersamaey** [comment]
+1

**Comment by samoudi2006** [comment]
module is not compatible M2.2

**Comment by Tjitse-E** [comment]
@woutersamaey , @samoudi2006 , i've forked the repo and added support for M2.2. myself. Checkout PR #16. Everything works fine here with M2.2 and PHP 7.1.

**Comment by gewaechshaus** [comment]
@Tjitse-E - many thanks! 
Can you edit the faqs in backend? I am still running into

    Class PHPCuongFaqFaqGridDataProvider does not exist

**Comment by Tjitse-E** [comment]
@gewaechshaus I don't have any troubles editing faqs in the backend. What steps are you taking exactly?

**Comment by gewaechshaus** [comment]
@Tjitse-E  - I just cloned your repo and did a setup: upgrade di:compile etc., Think I will have to investigate it... Maybe just missing files.

**Comment by moneef** [comment]
Hey @Tjitse-E,

i'm facing few issues with this module i hope you could help me as i'm currently broke and the author ask for fee on requests and sure ill pay him or you when i get funds.

1- first issue is with `.html` appending how can i remove it or add an option on adminhtml to chose to append it or not.

2- second issue with non-latin letters, when i input Arabic letters for category name its URL dosn't work anymore

**Comment by Tjitse-E** [comment]
@moneef please open a new issue for this, this issue is about Magento 2.2 compatibility

**Comment by moneef** [comment]
@Tjitse-E sure. thanks for guiding me.

**Comment by gewaechshaus** [comment]
@Tjitse-E - see PR https://github.com/php-cuong/magento2-faqs-extensions/pull/18 for fixing the issue I described above...
