### ISSUE TITLE
Incompatible argument type: Required type

### ISSUE THREAD

**Issue by Ralfefernandes** [php-cuong/magento2-faqs-extensions#19]
By running the command: php bin/magento setup:di:compile: 

Please re-run Magento compile command. Use the command "setup:di:compile"
ralfe@hp:/var/www/html/magento2$ sudo php bin/magento setup:di:compileCompilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% < 1 sec 50.0 Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 52.0 Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec Repositories code generation... 2/7 [========>-------------------]  28% 4 secs 1Service data attributes generation... 2/7 [========>-------------------]  28% 4 Service data attributes generation... 3/7 [============>---------------]  42% 4 Application code generator... 3/7 [============>---------------]  42% 4 secs 156Application code generator... 4/7 [================>-----------]  57% 6 secs 176Interceptors generation... 4/7 [================>-----------]  57% 6 secs 176.0 Interceptors generation... 5/7 [====================>-------]  71% 11 secs 192.0Area configuration aggregation... 5/7 [====================>-------]  71% 11 secArea configuration aggregation... 6/7 [========================>---]  85% 14 secInterception cache generation... 6/7 [========================>---]  85% 14 secs 258.0 MiBErrors during compilation:
	PHPCuong\Faq\Model\ResourceModel\Faqcat
		Incompatible argument type: Required type: string. Actual type: \PHPCuong\Faq\Model\ResourceModel\connectionName; File: 
/var/www/html/magento2/vendor/php-cuong/magento2-faqs-extensions/Model/ResourceModel/Faqcat.php

	PHPCuong\Faq\Model\ResourceModel\Faq\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \PHPCuong\Faq\Model\ResourceModel\Faq\Grid\connection; File: 
/var/www/html/magento2/vendor/php-cuong/magento2-faqs-extensions/Model/ResourceModel/Faq/Grid/Collection.php

	PHPCuong\Faq\Model\ResourceModel\Faqcat\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \PHPCuong\Faq\Model\ResourceModel\Faqcat\Grid\connection; File: 
/var/www/html/magento2/vendor/php-cuong/magento2-faqs-extensions/Model/ResourceModel/Faqcat/Grid/Collection.php

Total Errors Count: 3

                                           
  [Magento\Framework\Validator\Exception]  
  Error during compilation

**Comment by php-cuong** [comment]
@Ralfefernandes The problem was fixed in the version 2.1.4

**Comment by Ralfefernandes** [comment]
But i tested on Magento version 2.2.0

**Comment by php-cuong** [comment]
I mean, the FAQs extension version 2.1.4, please run composer update
