### ISSUE TITLE
magento2  ver 2.1.3 click add new faq button in the backend,  shows many errors

### ISSUE THREAD

**Issue by oppssssss** [php-cuong/magento2-faqs-extensions#2]
![image](https://cloud.githubusercontent.com/assets/19888056/22049558/0f83a77c-dd6f-11e6-922c-46cf2932551f.png)

**Comment by rizwan4317** [comment]
to add category and FAQ form is not showing in magento 2.1.3 see the [screenshot](https://screenshot.net/8vp0jbm)

**Comment by mironsoft75** [comment]
This does not work in 2.1.3. No form is displayed when editing or re-creating categories or FAQs

**Comment by php-cuong** [comment]
You should download all the source code with the latest version to your computer

**Comment by mironsoft75** [comment]
I have last version (master) installed. That did not help. The form is not displayed. 
In the log is: [2017-03-08 22:22:34] main.CRITICAL: Warning: htmlspecialchars () expects parameter 1 to be string, array given in ..... vendor / magento / framework / Data / Form / Element / AbstractElement.php on line 286 [] []

![bild](https://cloud.githubusercontent.com/assets/25805280/23727475/8120ab72-0458-11e7-884f-0c5f8c17401c.PNG)

**Comment by ramanvirtuos** [comment]
Is anyone resolve the issue with Magento 2.1.3

We are not able to view the FAQ ADD/EDIT form. Kindly fix this or send me updated branch access

**Comment by mironsoft75** [comment]
Please, too. This does not work with versions 2.1.3 / 2.1.4 / 2.1.5. Under 2.1.3 I have not tested.

**Comment by ramanvirtuos** [comment]
@php-cuong kindly resolve the issue with Version 2.1.3 or upper.

**Comment by mironsoft75** [comment]
I have mean, I have not tested with version 2.1.2. Otherwise you see the picture above, I use version 2.1.3 and it is blank page displayed. I do not install with the composer. Can it be that in the ZIP not all files are

**Comment by ramanvirtuos** [comment]
@mironsoft75  @php-cuong  it's not working with composer . I am getting same error

Exception #0 (Exception): Warning: htmlspecialchars() expects parameter 1 to be string, array given

**Comment by ramanvirtuos** [comment]
issue resolved. I am able to get Add/Edit form on Magento 2.1.x

**Comment by Aditi321** [comment]
@ramanvirtuos  how did u resolved the issue

**Comment by Aditi321** [comment]
we are facing the same issue in magento 2.0.13

**Comment by ramanvirtuos** [comment]
Hi,

You have to update the PHPCuong\Faq\Block\Adminhtml\Faq\Edit\Tab\Websites.php

Function Name: _prepareForm

Comment this function and replace with following Code:

 /**
     * Prepare form before rendering HTML
     *
     * @return $this
     */
    protected function _prepareForm()
    {
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();

        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('FAQ in Websites')]);

        $this->_addElementTypes($fieldset);

        $formData = $this->_coreRegistry->registry('phpcuong_faq');

        /**
         * Check is single store mode
         */

        if (!$this->_storeManager->isSingleStoreMode()) {
            $storeField = $fieldset->addField(
                'store_id',
                'multiselect',
                [
                    'name' => 'stores[]',
                    'label' => __('Store View'),
                    'title' => __('Store View'),
                    'required' => true,
                    'values' => $this->_systemStore->getStoreValuesForForm(false, true)
                ]
            );
            $renderer = $this->getLayout()->createBlock(
                'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
            );
            $storeField->setRenderer($renderer);
        } else {
            $fieldset->addField(
                'store_id',
                'hidden',
                ['name' => 'stores[]', 'value' => $this->_storeManager->getStore(true)->getId()]
            );
            $formData->setStoreId($this->_storeManager->getStore(true)->getId());
        }

 	$data = $formData->getData();
        $data['store_id'] = $formData->getStores();
        $form->setValues($data);

        $this->setForm($form);

       // $this->setForm($form);

        return parent::_prepareForm();
    }

**Comment by Aditi321** [comment]
Exception #0 (Exception): Warning: htmlspecialchars() expects parameter 1 to be string, array given

we are getting above error while adding faq category and faq in magento 2.0.13

**Comment by Aditi321** [comment]
error is not resolved after Comment this function and replace with following Code:

/**
* Prepare form before rendering HTML
*
* @return $this
/
protected function _prepareForm()
{
/* @var \Magento\Framework\Data\Form $form */
$form = $this->_formFactory->create();

    $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('FAQ in Websites')]);

    $this->_addElementTypes($fieldset);

    $formData = $this->_coreRegistry->registry('phpcuong_faq');

    /**
     * Check is single store mode
     */

    if (!$this->_storeManager->isSingleStoreMode()) {
        $storeField = $fieldset->addField(
            'store_id',
            'multiselect',
            [
                'name' => 'stores[]',
                'label' => __('Store View'),
                'title' => __('Store View'),
                'required' => true,
                'values' => $this->_systemStore->getStoreValuesForForm(false, true)
            ]
        );
        $renderer = $this->getLayout()->createBlock(
            'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
        );
        $storeField->setRenderer($renderer);
    } else {
        $fieldset->addField(
            'store_id',
            'hidden',
            ['name' => 'stores[]', 'value' => $this->_storeManager->getStore(true)->getId()]
        );
        $formData->setStoreId($this->_storeManager->getStore(true)->getId());
    }

$data = $formData->getData();
    $data['store_id'] = $formData->getStores();
    $form->setValues($data);

    $this->setForm($form);

   // $this->setForm($form);

    return parent::_prepareForm();
}

**Comment by Aditi321** [comment]
we are facing the same issue while adding categories in FAQ in magento 2.0.13

**Comment by nilarocks** [comment]
I have changed `$formData->setStores($this->_storeManager->getStore(true)->getId());` instead of `$formData->setStoreId($this->_storeManager->getStore(true)->getId());` 

and working fine. Add/edit screen working fine

**Comment by sbakker12** [comment]
Thanks nilarocks! it works

**Comment by sbakker12** [comment]
Hi nila,

Can you post your website.php file? I still can't add category :(

**Comment by sbakker12** [comment]
PHPCuong\Faq\Block\Adminhtml\Faqcat\Edit\Tab\Websites.php

<?php

/**
 *
 * @Author              Ngo Quang Cuong <bestearnmoney87@gmail.com>
 * @Date                2016-12-19 23:54:01
 * @Last modified by:   nquangcuong
 * @Last Modified time: 2016-12-24 15:30:44
 */

namespace PHPCuong\Faq\Block\Adminhtml\Faqcat\Edit\Tab;

use Magento\Store\Model\Store;

class Websites extends \Magento\Backend\Block\Widget\Form\Generic implements
    \Magento\Backend\Block\Widget\Tab\TabInterface
{
    /**
     * Core registry
     *
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;

    /**
     * @var \Magento\Store\Model\System\Store
     */
    protected $_systemStore;

    /**
     * @param \Magento\Store\Model\System\Store $systemStore
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Framework\Data\FormFactory $formFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Store\Model\System\Store $systemStore,
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        array $data = []
    ) {
        $this->_systemStore = $systemStore;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setActive(true);
    }

    /**
     * Prepare label for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabLabel()
    {
        return __('FAQ Category in Websites');
    }

    /**
     * Prepare title for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabTitle()
    {
        return $this->getTabLabel();
    }

    /**
     * Returns status flag about this tab can be showen or not
     *
     * @return true
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * Returns status flag about this tab hidden or not
     *
     * @return true
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     */
    protected function _prepareForm()
    {
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();

        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('FAQ Category in Websites')]);

        $this->_addElementTypes($fieldset);

        $formData = $this->_coreRegistry->registry('phpcuong_faqcat');

        /**
         * Check is single store mode
         */
        if (!$this->_storeManager->hasSingleStore()) {
            $field = $fieldset->addField(
                'stores',
                'multiselect',
                [
                    'label' => __('Stores View'),
                    'title' => __('Stores View'),
                    'required' => true,
                    'name' => 'stores[]',
                    'values' => $this->_systemStore->getStoreValuesForForm(false, true)
                ]
            );
            $renderer = $this->getLayout()->createBlock(
                'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
            );
            $field->setRenderer($renderer);
            $formData->setSelectStores($formData->getStores());
        } else {
            $fieldset->addField(
                'stores',
                'hidden',
                ['name' => 'stores[]', 'value' => $this->_storeManager->getStore(true)->getId()]
            );
            $formData->setStores($this->_storeManager->getStore(true)->getId());
        }

        if ($formData) {
            if ($formData->getStores() == null) {
                $formData->setStores([Store::DEFAULT_STORE_ID]);
            }
            $form->setValues($formData->getData());
        }

        $this->setForm($form);

        return parent::_prepareForm();
    }
}

**Comment by sbakker12** [comment]
`<?php

/**
 *
 * @Author              Ngo Quang Cuong <bestearnmoney87@gmail.com>
 * @Date                2016-12-19 23:54:01
 * @Last modified by:   nquangcuong
 * @Last Modified time: 2016-12-24 15:30:44
 */

namespace PHPCuong\Faq\Block\Adminhtml\Faqcat\Edit\Tab;

use Magento\Store\Model\Store;

class Websites extends \Magento\Backend\Block\Widget\Form\Generic implements
    \Magento\Backend\Block\Widget\Tab\TabInterface
{
    /**
     * Core registry
     *
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;

    /**
     * @var \Magento\Store\Model\System\Store
     */
    protected $_systemStore;

    /**
     * @param \Magento\Store\Model\System\Store $systemStore
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Framework\Data\FormFactory $formFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Store\Model\System\Store $systemStore,
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        array $data = []
    ) {
        $this->_systemStore = $systemStore;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setActive(true);
    }

    /**
     * Prepare label for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabLabel()
    {
        return __('FAQ Category in Websites');
    }

    /**
     * Prepare title for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabTitle()
    {
        return $this->getTabLabel();
    }

    /**
     * Returns status flag about this tab can be showen or not
     *
     * @return true
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * Returns status flag about this tab hidden or not
     *
     * @return true
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     */
    protected function _prepareForm()
    {
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();

        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('FAQ Category in Websites')]);

        $this->_addElementTypes($fieldset);

        $formData = $this->_coreRegistry->registry('phpcuong_faqcat');

        /**
         * Check is single store mode
         */
        if (!$this->_storeManager->hasSingleStore()) {
            $field = $fieldset->addField(
                'stores',
                'multiselect',
                [
                    'label' => __('Stores View'),
                    'title' => __('Stores View'),
                    'required' => true,
                    'name' => 'stores[]',
                    'values' => $this->_systemStore->getStoreValuesForForm(false, true)
                ]
            );
            $renderer = $this->getLayout()->createBlock(
                'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
            );
            $field->setRenderer($renderer);
            $formData->setSelectStores($formData->getStores());
        } else {
            $fieldset->addField(
                'stores',
                'hidden',
                ['name' => 'stores[]', 'value' => $this->_storeManager->getStore(true)->getId()]
            );
            $formData->setStores($this->_storeManager->getStore(true)->getId());
        }

        if ($formData) {
            if ($formData->getStores() == null) {
                $formData->setStores([Store::DEFAULT_STORE_ID]);
            }
            $form->setValues($formData->getData());
        }

        $this->setForm($form);

        return parent::_prepareForm();
    }
}
`

**Comment by sbakker12** [comment]
`<?php

/**
 *
 * @Author              Ngo Quang Cuong <bestearnmoney87@gmail.com>
 * @Date                2016-12-17 01:11:17
 * @Last modified by:   nquangcuong
 * @Last Modified time: 2016-12-24 15:25:43
 */

namespace PHPCuong\Faq\Block\Adminhtml\Faq\Edit\Tab;

use Magento\Store\Model\Store;

class Websites extends \Magento\Backend\Block\Widget\Form\Generic implements
    \Magento\Backend\Block\Widget\Tab\TabInterface
{
    /**
     * Core registry
     *
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;

    /**
     * @var \Magento\Store\Model\System\Store
     */
    protected $_systemStore;

    /**
     * @param \Magento\Store\Model\System\Store $systemStore
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Framework\Data\FormFactory $formFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Store\Model\System\Store $systemStore,
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        array $data = []
    ) {
        $this->_systemStore = $systemStore;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setActive(true);
    }

    /**
     * Prepare label for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabLabel()
    {
        return __('FAQ in Websites');
    }

    /**
     * Prepare title for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabTitle()
    {
        return $this->getTabLabel();
    }

    /**
     * Returns status flag about this tab can be showen or not
     *
     * @return true
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * Returns status flag about this tab hidden or not
     *
     * @return true
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     */
    protected function _prepareForm()
    {
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();

        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('FAQ in Websites')]);

        $this->_addElementTypes($fieldset);

        $formData = $this->_coreRegistry->registry('phpcuong_faq');

        /**
         * Check is single store mode
         */
        if (!$this->_storeManager->hasSingleStore()) {
            $field = $fieldset->addField(
                'stores',
                'multiselect',
                [
                    'label' => __('Stores View'),
                    'title' => __('Stores View'),
                    'required' => true,
                    'name' => 'stores[]',
                    'values' => $this->_systemStore->getStoreValuesForForm(false, true)
                ]
            );
            $renderer = $this->getLayout()->createBlock(
                'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
            );
            $field->setRenderer($renderer);
            $formData->setSelectStores($formData->getStores());
        } else {
            $fieldset->addField(
                'stores',
                'hidden',
                ['name' => 'stores[]', 'value' => $this->_storeManager->getStore(true)->getId()]
            );
            $formData->setStores($this->_storeManager->getStore(true)->getId());
        }

        if ($formData) {
            if ($formData->getStores() == null) {
                $formData->setStores([Store::DEFAULT_STORE_ID]);
            }
            $form->setValues($formData->getData());
        }

        $this->setForm($form);

        return parent::_prepareForm();
    }
} `

**Comment by sbakker12** [comment]
Above code works with 2.16 :)

**Comment by kevingreek** [comment]
i have correct edit-add form at 2.1.6 CE but only for Faq, not for Categories!! Any idea?

**Comment by govereem** [comment]
You need to change 2 files
/app/code/PHPCuong/Faq/Block/Adminhtml/Faqcat/Edit/Tab/Websites.php
/app/code/PHPCuong/Faq/Block/Adminhtml/Faq/Edit/Tab/Websites.php

/Faqcat/Edit/Tab/Websites.php change on row 139
$formData->setSelectStores($this->_storeManager->getStore(true)->getId()); TO
$formData->setStores($this->_storeManager->getStore(true)->getId());

/Faq/Edit/Tab/Websites.php  change on row 139
$formData->setSelectStores($this->_storeManager->getStore(true)->getId()); TO
$formData->setStores($this->_storeManager->getStore(true)->getId());

Tested it on 2.17 CE

**Comment by sneha-panchal** [comment]
Please update these 2 files :

app\code\PHPCuong\Faq\Block\Adminhtml\Faq\Edit\Tab\Websites.php

`<?php

/**
 *
 * @Author              Ngo Quang Cuong <bestearnmoney87@gmail.com>
 * @Date                2016-12-17 01:11:17
 * @Last modified by:   nquangcuong
 * @Last Modified time: 2016-12-24 15:25:43
 */

namespace PHPCuong\Faq\Block\Adminhtml\Faq\Edit\Tab;

use Magento\Store\Model\Store;

class Websites extends \Magento\Backend\Block\Widget\Form\Generic implements
    \Magento\Backend\Block\Widget\Tab\TabInterface
{
    /**
     * Core registry
     *
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;

    /**
     * @var \Magento\Store\Model\System\Store
     */
    protected $_systemStore;

    /**
     * @param \Magento\Store\Model\System\Store $systemStore
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Framework\Data\FormFactory $formFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Store\Model\System\Store $systemStore,
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        array $data = []
    ) {
        $this->_systemStore = $systemStore;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setActive(true);
    }

    /**
     * Prepare label for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabLabel()
    {
        return __('FAQ in Websites');
    }

    /**
     * Prepare title for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabTitle()
    {
        return $this->getTabLabel();
    }

    /**
     * Returns status flag about this tab can be showen or not
     *
     * @return true
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * Returns status flag about this tab hidden or not
     *
     * @return true
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     */
    protected function _prepareForm()
    {
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();

        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('FAQ in Websites')]);

        $this->_addElementTypes($fieldset);

        $formData = $this->_coreRegistry->registry('phpcuong_faq');

        /**
         * Check is single store mode
         */
       // if (!$this->_storeManager->hasSingleStore()) {
            $field = $fieldset->addField(
                'stores',
                'multiselect',
                [
                    'label' => __('Stores View'),
                    'title' => __('Stores View'),
                    'required' => true,
                    'name' => 'stores[]',
                    'values' => $this->_systemStore->getStoreValuesForForm(false, true)
                ]
            );
            $renderer = $this->getLayout()->createBlock(
                'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
            );
            $field->setRenderer($renderer);
            $formData->setSelectStores($formData->getStores());
        /*} else {
            $fieldset->addField(
                'stores',
                'hidden',
                ['name' => 'stores[]', 'value' => $this->_storeManager->getStore(true)->getId()]
            );
            $formData->setSelectStores($this->_storeManager->getStore(true)->getId());
        }*/

        if ($formData) {
            if ($formData->getStores() == null) {
                $formData->setStores([Store::DEFAULT_STORE_ID]);
            }
            $form->setValues($formData->getData());
        }

        $this->setForm($form);

        return parent::_prepareForm();
    }
}
`

app\code\PHPCuong\Faq\Block\Adminhtml\Faqcat\Edit\Tab\Websites.php


`<?php

/**
 *
 * @Author              Ngo Quang Cuong <bestearnmoney87@gmail.com>
 * @Date                2016-12-19 23:54:01
 * @Last modified by:   nquangcuong
 * @Last Modified time: 2016-12-24 15:30:44
 */

namespace PHPCuong\Faq\Block\Adminhtml\Faqcat\Edit\Tab;

use Magento\Store\Model\Store;

class Websites extends \Magento\Backend\Block\Widget\Form\Generic implements
    \Magento\Backend\Block\Widget\Tab\TabInterface
{
    /**
     * Core registry
     *
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;

    /**
     * @var \Magento\Store\Model\System\Store
     */
    protected $_systemStore;

    /**
     * @param \Magento\Store\Model\System\Store $systemStore
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Framework\Data\FormFactory $formFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Store\Model\System\Store $systemStore,
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        array $data = []
    ) {
        $this->_systemStore = $systemStore;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setActive(true);
    }

    /**
     * Prepare label for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabLabel()
    {
        return __('FAQ Category in Websites');
    }

    /**
     * Prepare title for tab
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabTitle()
    {
        return $this->getTabLabel();
    }

    /**
     * Returns status flag about this tab can be showen or not
     *
     * @return true
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * Returns status flag about this tab hidden or not
     *
     * @return true
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     */
    protected function _prepareForm()
    {
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();

        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('FAQ Category in Websites')]);

        $this->_addElementTypes($fieldset);

        $formData = $this->_coreRegistry->registry('phpcuong_faqcat');

        /**
         * Check is single store mode
         */
      //  if (!$this->_storeManager->hasSingleStore()) {
            $field = $fieldset->addField(
                'stores',
                'multiselect',
                [
                    'label' => __('Stores View'),
                    'title' => __('Stores View'),
                    'required' => true,
                    'name' => 'stores[]',
                    'values' => $this->_systemStore->getStoreValuesForForm(false, true)
                ]
            );
            $renderer = $this->getLayout()->createBlock(
                'Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset\Element'
            );
            $field->setRenderer($renderer);
            $formData->setSelectStores($formData->getStores());
       /* } else {
            $fieldset->addField(
                'stores',
                'hidden',
                ['name' => 'stores[]', 'value' => $this->_storeManager->getStore(true)->getId()]
            );
            $formData->setSelectStores($this->_storeManager->getStore(true)->getId());
        }*/

        if ($formData) {
            if ($formData->getStores() == null) {
                $formData->setStores([Store::DEFAULT_STORE_ID]);
            }
            $form->setValues($formData->getData());
        }

        $this->setForm($form);

        return parent::_prepareForm();
    }
}
`


Above code is tested and also working in magento CE 2.1.x.

Thanks..

**Comment by php-cuong** [comment]
The problem was fixed, please pull the latest codes.
