### ISSUE TITLE
CSS does not import when the css files are merged

### ISSUE THREAD

**Issue by dazz397** [php-cuong/magento2-faqs-extensions#20]
The FAQ works fine but the icons do not show and the formatting is off when I moved the site to production and turned on js/css merging/bundling. 

In Chrome is shows the following errors:
/static/version1511980792/_cache/merged/faq-extension/style.css net::ERR_ABORTED
/static/version1511980792/_cache/merged/bootstrap.css net::ERR_ABORTED

**Comment by php-cuong** [comment]
@dazz397 What is the version of Magento 2 you are using?

**Comment by dazz397** [comment]
Magento 2.1.9 and 2.1.10, happens on both. It only happens when css is merged.

**Comment by php-cuong** [comment]
I tested in Magento 2.1.9 it worked perfectly! You can try to install Magento 2.1.9 then you install this extension. Let me know if you still got the issues.

**Comment by dazz397** [comment]
This still does not work.  Here is an example:
https://www.invisiclean.com/faqs.html

If you view 
https://www.invisiclean.com/static/version1513321265/_cache/merged/91c6c88e52e97a582ed8bf0e5638ae58.min.css

There is a line which does not exist
import '../PHPCuong_Faq/css/faq-extension/style.css';

Also I had to remove bootstrap.css because the theme I am using already uses bootstrap and was conflicting with yours.

Thanks Jay

**Comment by AleksZelenchuk** [comment]
Hi, I'm using Magento 2.2.2 and i've got same problem when moved to production and enable css merge. Although it work's fine on local. Is there anything i can change in code so it would work on production too?
