### ISSUE TITLE
magento2 ver 2.1.3 click add new Category button in the backend, shows many errors 

### ISSUE THREAD

**Issue by Aditi321** [php-cuong/magento2-faqs-extensions#3]
Warning: htmlspecialchars() expects parameter 1 to be string, array given in C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\AbstractElement.php on line 286
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'htmlspecialchar...', 'C:\\Xampp\\htdocs...', 286, Array)
#1 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\AbstractElement.php(286): htmlspecialchars(Array, 2)
#2 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\AbstractElement.php(302): Magento\Framework\Data\Form\Element\AbstractElement->_escape(Array)
#3 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\AbstractElement.php(365): Magento\Framework\Data\Form\Element\AbstractElement->getEscapedValue()
#4 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\view\adminhtml\templates\widget\form\renderer\fieldset\element.phtml(31): Magento\Framework\Data\Form\Element\AbstractElement->getElementHtml()
#5 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\\Xampp\\htdocs...')
#6 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element), 'C:/Xampp/htdocs...', Array)
#7 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/Xampp/htdocs...')
#8 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#9 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#10 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\Block\Widget\Form\Renderer\Fieldset\Element.php(45): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\AbstractElement.php(465): Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element->render(Object(Magento\Framework\Data\Form\Element\Hidden))
#12 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\AbstractElement.php(479): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#13 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\Fieldset.php(229): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#14 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\Fieldset.php(106): Magento\Framework\Data\Form\Element\Fieldset->_elementsToHtml(Array)
#15 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\view\adminhtml\templates\widget\form\renderer\fieldset.phtml(84): Magento\Framework\Data\Form\Element\Fieldset->getBasicChildrenHtml()
#16 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\\Xampp\\htdocs...')
#17 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Form\Renderer\Fieldset), 'C:/Xampp/htdocs...', Array)
#18 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/Xampp/htdocs...')
#19 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#20 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#21 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\Block\Widget\Form\Renderer\Fieldset.php(45): Magento\Framework\View\Element\AbstractBlock->toHtml()
#22 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\AbstractElement.php(465): Magento\Backend\Block\Widget\Form\Renderer\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset))
#23 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form\Element\AbstractElement.php(479): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#24 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form.php(322): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#25 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Data\Form.php(337): Magento\Framework\Data\Form->toHtml()
#26 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\Block\Widget\Form.php(98): Magento\Framework\Data\Form->getHtml()
#27 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\view\adminhtml\templates\widget\form.phtml(15): Magento\Backend\Block\Widget\Form->getFormHtml()
#28 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\\Xampp\\htdocs...')
#29 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(PHPCuong\Faq\Block\Adminhtml\Faqcat\Edit\Tab\Websites), 'C:/Xampp/htdocs...', Array)
#30 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/Xampp/htdocs...')
#31 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#32 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#33 C:\Xampp\htdocs\MagentoCE\app\code\PHPCuong\Faq\Block\Adminhtml\Faqcat\Edit\Tabs.php(61): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Element\AbstractBlock.php(262): PHPCuong\Faq\Block\Adminhtml\Faqcat\Edit\Tabs->_prepareLayout()
#35 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Layout\Generator\Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#36 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Layout\GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#37 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#38 C:\Xampp\htdocs\MagentoCE\var\generation\Magento\Framework\View\Layout\Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#39 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Layout\Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#40 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Page\Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#41 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Layout\Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#42 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#43 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\View\Layout.php(859): Magento\Framework\View\Layout->build()
#44 C:\Xampp\htdocs\MagentoCE\var\generation\Magento\Framework\View\Layout\Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#45 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\Model\View\Result\Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#46 C:\Xampp\htdocs\MagentoCE\var\generation\Magento\Backend\Model\View\Result\Page\Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('PHPCuong_Faq::f...')
#47 C:\Xampp\htdocs\MagentoCE\app\code\PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit.php(61): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('PHPCuong_Faq::f...')
#48 C:\Xampp\htdocs\MagentoCE\app\code\PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit.php(98): PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit->_initAction()
#49 C:\Xampp\htdocs\MagentoCE\var\generation\PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor.php(24): PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit->execute()
#50 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\App\Action\Action.php(102): PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor->execute()
#51 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\App\AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#52 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#53 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#54 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Chain\Chain.php(70): PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor->___callParent('dispatch', Array)
#55 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('PHPCuong\\Faq\\Co...', 'dispatch', Object(PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor), Array, 'adminAuthentica...')
#56 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#57 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#58 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array)
#59 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('PHPCuong\\Faq\\Co...', 'dispatch', Object(PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor), Array, 'designLoader')
#60 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\App\Action\Plugin\Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#61 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#62 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array)
#63 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('PHPCuong\\Faq\\Co...', 'dispatch', Object(PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor), Array, 'adminMassaction...')
#64 C:\Xampp\htdocs\MagentoCE\vendor\magento\module-backend\App\Action\Plugin\MassactionKey.php(33): PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#65 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#66 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Interceptor.php(143): call_user_func_array(Array, Array)
#67 C:\Xampp\htdocs\MagentoCE\var\generation\PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor.php(39): PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#68 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\App\FrontController.php(55): PHPCuong\Faq\Controller\Adminhtml\Faqcat\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#69 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#70 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#71 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#72 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#73 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#74 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#75 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\Interception\Interceptor.php(143): call_user_func_array(Array, Array)
#76 C:\Xampp\htdocs\MagentoCE\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#77 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\App\Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#78 C:\Xampp\htdocs\MagentoCE\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#79 C:\Xampp\htdocs\MagentoCE\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#80 {main}

**Comment by Aditi321** [comment]
@ramanvirtuos  How to resolve this issue?

**Comment by nilarocks** [comment]
Hello,

Check my answer [here](https://github.com/php-cuong/magento2-faqs-extensions/issues/2)

**Comment by php-cuong** [comment]
The problem was fixed, please pull the latest codes.
