### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by Tonop** [php-cuong/magento2-faqs-extensions#4]
Hi,

Thanks for great extention. How to translate to different language? I dont see a scv file, can you guide me?

**Comment by php-cuong** [comment]
Multiple languages aren't supported at the moment. It am going to be updated later.

PHPCuong

**Comment by justsign** [comment]
Please can you tell me when you have it ready?
I need Dutch for my shop (https://www.bedrukt.shop)

Regards,
Rob van Westrop

**Comment by php-cuong** [comment]
I think you need to pay me fee for this function. It is not free at the moment.

**Comment by justsign** [comment]
Okay, please send me a email what the price will be.

**Comment by php-cuong** [comment]
It is $30, I use the payment method paypal

**Comment by justsign** [comment]
Okay, please give me your paypal account and i will pay you

Verstuurd vanaf mijn iPad

**Comment by php-cuong** [comment]
This is my fan page https://www.facebook.com/giaphugroupcom/ please contact me now, We will discuss about your requirements
