### ISSUE TITLE
Yor extension is not working properly in magento 2.1.6.

### ISSUE THREAD

**Issue by sup077** [php-cuong/magento2-faqs-extensions#6]
![faq issue](https://user-images.githubusercontent.com/28781226/26923844-10cae18e-4c61-11e7-9191-a7d5fcbb4897.png)
I facing this kind of issue. I am not able to make any kind of changes in your extension. Please help me to resolve this issue.
Eagerly waiting for your positive reply.
Thanks & Regards
Supriti kashyap

**Comment by sup077** [comment]
The extension name is magento2-faqs-extensions. I am downloaded it from https://github.com/php-cuong/magento2-faqs-extensions .

**Comment by sneha-panchal** [comment]
Please check [this ans](https://github.com/php-cuong/magento2-faqs-extensions/issues/7#issuecomment-310586011)

**Comment by php-cuong** [comment]
The problem was fixed, please pull the latest code.
