### ISSUE TITLE
Clickable Links or Videos

### ISSUE THREAD

**Issue by atrane21** [php-cuong/magento2-faqs-extensions#8]
Hi, 
I just installed this extension and it's working great so far. I was curious is there anyway to make links clickable in the dropdowns or show embed youtube videos? Making links clickable in the editor doesn't translate properly to the dropdown. Same with videos.

Thank you!

**Comment by php-cuong** [comment]
I don't understand your problem. Please include a snapshot or contact me on the fanpage https://www.facebook.com/giaphugroupcom/

**Comment by atrane21** [comment]
If you go to our page (https://dutchwaregear.com/faqs.html) and if you click on the + next to "How do i rig my tarp with hardware" you'll see there is a youtube link there. That link is not clickable. I have it setup correct when making the FAQ that it should be a clickable link leading to that URL but it still does not work. 

Also, i have tried embedding the youtube video itself in the same area but when you click the + it just shows up blank and doesn't show the youtube video.

**Comment by php-cuong** [comment]
Hi, I updated something to resolve your problem. Please using the latest version of this extension.
